import type { GameQuestion } from '../types';

/** Scenario-based akhlaq (good character) — practical Islamic manners. */
export const CHARACTER_QUESTIONS: GameQuestion[] = [
  {
    id: 'char-1',
    gameId: 'character',
    category: 'character',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Your friend drops their books. What should you do?',
    choices: [
      { id: 'a', label: 'Laugh' },
      { id: 'b', label: 'Walk away' },
      { id: 'c', label: 'Help them' },
      { id: 'd', label: 'Hide the books' },
    ],
    correctChoiceId: 'c',
    explanation: 'Islam teaches us to help others and show good character.',
    hint: 'Choose the kind action.',
  },
  {
    id: 'char-2',
    gameId: 'character',
    category: 'character',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'You broke a cup by mistake. What should you do?',
    choices: [
      { id: 'a', label: 'Tell the truth and say sorry' },
      { id: 'b', label: 'Blame someone else' },
      { id: 'c', label: 'Hide it and stay quiet' },
    ],
    correctChoiceId: 'a',
    explanation: 'Muslims tell the truth and take responsibility.',
    hint: 'Honesty is part of good character.',
  },
  {
    id: 'char-3',
    gameId: 'character',
    category: 'character',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Your parents ask for help. What should you do?',
    choices: [
      { id: 'a', label: 'Help them kindly' },
      { id: 'b', label: 'Ignore them' },
      { id: 'c', label: 'Get angry' },
    ],
    correctChoiceId: 'a',
    explanation: 'Islam teaches us to respect and help our parents.',
    hint: 'Parents deserve kindness.',
  },
  {
    id: 'char-4',
    gameId: 'character',
    category: 'character',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'You promised to share a toy. What should you do?',
    choices: [
      { id: 'a', label: 'Keep your promise' },
      { id: 'b', label: 'Change your mind without care' },
      { id: 'c', label: 'Take it back and shout' },
    ],
    correctChoiceId: 'a',
    explanation: 'Keeping promises is part of good Islamic character.',
    hint: 'A promise should be kept.',
  },
  {
    id: 'char-5',
    gameId: 'character',
    category: 'character',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Someone is waiting for a turn. What should you do?',
    choices: [
      { id: 'a', label: 'Wait patiently for your turn' },
      { id: 'b', label: 'Push to the front' },
      { id: 'c', label: 'Shout at them' },
    ],
    correctChoiceId: 'a',
    explanation: 'Patience and fairness are beautiful Islamic manners.',
    hint: 'Patience is a great quality.',
  },
  {
    id: 'char-6',
    gameId: 'character',
    category: 'character',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'A classmate looks sad and alone. What is a good choice?',
    choices: [
      { id: 'a', label: 'Be kind and include them' },
      { id: 'b', label: 'Make fun of them' },
      { id: 'c', label: 'Tell others to ignore them' },
    ],
    correctChoiceId: 'a',
    explanation: 'Good character means being kind and caring for others.',
    hint: 'Choose kindness.',
  },
  {
    id: 'char-7',
    gameId: 'character',
    category: 'character',
    ageGroups: ['teen_15_17', 'adult_18_plus', 'child_11_14'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'You hear gossip about someone. What should you do?',
    choices: [
      { id: 'a', label: 'Do not join in; protect their honor' },
      { id: 'b', label: 'Add more rumors' },
      { id: 'c', label: 'Spread it quickly' },
    ],
    correctChoiceId: 'a',
    explanation: 'Islam teaches us to guard people’s honor and avoid harmful talk.',
    hint: 'Protect others, do not harm them with words.',
  },
  {
    id: 'char-8',
    gameId: 'character',
    category: 'character',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'You have snacks and a friend has none. What should you do?',
    choices: [
      { id: 'a', label: 'Share with them' },
      { id: 'b', label: 'Eat everything secretly' },
      { id: 'c', label: 'Tease them' },
    ],
    correctChoiceId: 'a',
    explanation: 'Sharing is part of generosity and good character in Islam.',
    hint: 'Be generous.',
  },
];
