import type { GameQuestion } from '../types';

/** General Islamic knowledge — established basics only. */
export const KNOWLEDGE_QUESTIONS: GameQuestion[] = [
  {
    id: 'know-1',
    gameId: 'knowledge',
    category: 'islam_basics',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'How many pillars of Islam are there?',
    choices: [
      { id: 'a', label: '3' },
      { id: 'b', label: '5' },
      { id: 'c', label: '7' },
    ],
    correctChoiceId: 'b',
    explanation: 'There are five pillars of Islam.',
    hint: 'It is the same number as the daily prayers.',
  },
  {
    id: 'know-2',
    gameId: 'knowledge',
    category: 'islam_basics',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'What is the holy book of Muslims?',
    choices: [
      { id: 'a', label: 'The Qur’an' },
      { id: 'b', label: 'A storybook' },
      { id: 'c', label: 'A comic' },
    ],
    correctChoiceId: 'a',
    explanation: 'The Qur’an is the Word of Allah revealed to Prophet Muhammad ﷺ.',
    hint: 'Muslims recite it in Salah.',
  },
  {
    id: 'know-3',
    gameId: 'knowledge',
    category: 'islam_basics',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Muslims worship…',
    choices: [
      { id: 'a', label: 'Allah alone' },
      { id: 'b', label: 'Many gods' },
      { id: 'c', label: 'The sun' },
    ],
    correctChoiceId: 'a',
    explanation: 'Islam teaches Tawhid — worshipping Allah alone.',
    hint: 'There is only One God.',
  },
  {
    id: 'know-4',
    gameId: 'knowledge',
    category: 'quran',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Where do Muslims go for Hajj?',
    choices: [
      { id: 'a', label: 'Makkah' },
      { id: 'b', label: 'Any city' },
      { id: 'c', label: 'A random mountain' },
    ],
    correctChoiceId: 'a',
    explanation: 'Hajj is performed in and around Makkah.',
    hint: 'It is the city of the Ka‘bah.',
  },
  {
    id: 'know-5',
    gameId: 'knowledge',
    category: 'ramadan',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'In which month do Muslims fast?',
    choices: [
      { id: 'a', label: 'Ramadan' },
      { id: 'b', label: 'Any month randomly' },
      { id: 'c', label: 'Only in winter' },
    ],
    correctChoiceId: 'a',
    explanation: 'Muslims fast during the month of Ramadan.',
    hint: 'It is a blessed month of fasting.',
  },
  {
    id: 'know-6',
    gameId: 'knowledge',
    category: 'salah',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'What is the name of the Friday prayer?',
    choices: [
      { id: 'a', label: 'Jumu‘ah' },
      { id: 'b', label: 'Tarawih only' },
      { id: 'c', label: 'Eid only' },
    ],
    correctChoiceId: 'a',
    explanation: 'Jumu‘ah is the special Friday congregational prayer.',
    hint: 'It happens once a week on Friday.',
  },
  {
    id: 'know-7',
    gameId: 'knowledge',
    category: 'islam_basics',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Saying “Assalamu Alaikum” means…',
    choices: [
      { id: 'a', label: 'Peace be upon you' },
      { id: 'b', label: 'Goodbye forever' },
      { id: 'c', label: 'I am angry' },
    ],
    correctChoiceId: 'a',
    explanation: 'The Islamic greeting wishes peace upon others.',
    hint: 'It is a greeting of peace.',
  },
  {
    id: 'know-8',
    gameId: 'knowledge',
    category: 'hajj',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'What is the Ka‘bah?',
    choices: [
      { id: 'a', label: 'The sacred House of Allah in Makkah' },
      { id: 'b', label: 'A market stall' },
      { id: 'c', label: 'A mountain only for decoration' },
    ],
    correctChoiceId: 'a',
    explanation: 'The Ka‘bah is the sacred House of Allah in Makkah.',
    hint: 'Muslims face it in prayer.',
  },
  {
    id: 'know-9',
    gameId: 'knowledge',
    category: 'prophets',
    ageGroups: ['teen_15_17', 'adult_18_plus'],
    difficulty: 4,
    type: 'multiple_choice',
    prompt: 'Muslims believe in…',
    choices: [
      { id: 'a', label: 'All the Prophets of Allah, ending with Muhammad ﷺ' },
      { id: 'b', label: 'No Prophets' },
      { id: 'c', label: 'Only kings' },
    ],
    correctChoiceId: 'a',
    explanation:
      'Belief in the Prophets is part of faith, and Muhammad ﷺ is the final Messenger.',
    hint: 'Prophethood is a pillar of faith.',
  },
  {
    id: 'know-10',
    gameId: 'knowledge',
    category: 'islam_basics',
    ageGroups: ['child_3_6', 'child_7_10'],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Which building do Muslims go to for prayer together?',
    choices: [
      { id: 'a', label: 'A mosque' },
      { id: 'b', label: 'A playground only' },
      { id: 'c', label: 'A supermarket' },
    ],
    correctChoiceId: 'a',
    explanation: 'A mosque is a place where Muslims pray together.',
    hint: 'It is also called a masjid.',
  },
];
