import type { GameQuestion } from '../types';

/**
 * Prophet “Who Am I?” clues based on well-known Qur’anic accounts.
 * Uses respectful ﷺ wording. No invented stories or fabricated quotes.
 */
export const PROPHETS_QUESTIONS: GameQuestion[] = [
  {
    id: 'prophet-nuh-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: [],
    difficulty: 1,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'Allah commanded me to build the Ark.',
    choices: [
      { id: 'nuh', label: 'Nuh ﷺ' },
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'yunus', label: 'Yunus ﷺ' },
    ],
    correctChoiceId: 'nuh',
    answerLabel: 'Nuh ﷺ',
    explanation: 'Prophet Nuh ﷺ built the Ark by Allah’s command.',
    hint: 'Think of the great flood and the Ark.',
    sourceNote: 'Qur’an — account of Nuh and the Ark.',
  },
  {
    id: 'prophet-musa-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: [],
    difficulty: 1,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'Allah sent me to Pharaoh.',
    choices: [
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'ibrahim', label: 'Ibrahim ﷺ' },
      { id: 'isa', label: 'Isa ﷺ' },
    ],
    correctChoiceId: 'musa',
    answerLabel: 'Musa ﷺ',
    explanation: 'Prophet Musa ﷺ was sent to Pharaoh.',
    hint: 'He spoke to Pharaoh about worshipping Allah alone.',
  },
  {
    id: 'prophet-ibrahim-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: [],
    difficulty: 1,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'I was the father of Isma‘il ﷺ.',
    choices: [
      { id: 'ibrahim', label: 'Ibrahim ﷺ' },
      { id: 'nuh', label: 'Nuh ﷺ' },
      { id: 'yunus', label: 'Yunus ﷺ' },
    ],
    correctChoiceId: 'ibrahim',
    answerLabel: 'Ibrahim ﷺ',
    explanation: 'Prophet Ibrahim ﷺ was the father of Isma‘il ﷺ.',
    hint: 'He is called Khaleelullah — the close friend of Allah.',
  },
  {
    id: 'prophet-yunus-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'I was swallowed by a great fish, and I called upon Allah.',
    choices: [
      { id: 'yunus', label: 'Yunus ﷺ' },
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'nuh', label: 'Nuh ﷺ' },
    ],
    correctChoiceId: 'yunus',
    answerLabel: 'Yunus ﷺ',
    explanation: 'Prophet Yunus ﷺ called upon Allah from inside the fish.',
    hint: 'His story is connected to a great fish.',
  },
  {
    id: 'prophet-isa-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'My mother is Maryam (peace be upon her).',
    choices: [
      { id: 'isa', label: 'Isa ﷺ' },
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'ibrahim', label: 'Ibrahim ﷺ' },
    ],
    correctChoiceId: 'isa',
    answerLabel: 'Isa ﷺ',
    explanation: 'Prophet Isa ﷺ is the son of Maryam (peace be upon her).',
    hint: 'Maryam is his mother.',
  },
  {
    id: 'prophet-muhammad-1',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: [],
    difficulty: 1,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'I am the final Messenger of Allah.',
    choices: [
      { id: 'muhammad', label: 'Muhammad ﷺ' },
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'isa', label: 'Isa ﷺ' },
    ],
    correctChoiceId: 'muhammad',
    answerLabel: 'Muhammad ﷺ',
    explanation: 'Prophet Muhammad ﷺ is the final Messenger of Allah.',
    hint: 'He received the Qur’an.',
  },
  {
    id: 'prophet-ibrahim-2',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'With my son Isma‘il ﷺ, I raised the foundations of the Ka‘bah.',
    choices: [
      { id: 'ibrahim', label: 'Ibrahim ﷺ' },
      { id: 'nuh', label: 'Nuh ﷺ' },
      { id: 'yunus', label: 'Yunus ﷺ' },
    ],
    correctChoiceId: 'ibrahim',
    answerLabel: 'Ibrahim ﷺ',
    explanation: 'Prophet Ibrahim ﷺ and Isma‘il ﷺ raised the foundations of the Ka‘bah.',
    hint: 'Connected to the Ka‘bah in Makkah.',
    sourceNote: 'Qur’an 2:127 — raising the foundations of the House.',
  },
  {
    id: 'prophet-musa-2',
    gameId: 'prophets',
    category: 'prophets',
    ageGroups: ['teen_15_17', 'adult_18_plus', 'child_11_14'],
    difficulty: 3,
    type: 'clue',
    prompt: 'Who am I?',
    clue: 'Allah spoke to me at the sacred valley of Tuwa.',
    choices: [
      { id: 'musa', label: 'Musa ﷺ' },
      { id: 'ibrahim', label: 'Ibrahim ﷺ' },
      { id: 'isa', label: 'Isa ﷺ' },
    ],
    correctChoiceId: 'musa',
    answerLabel: 'Musa ﷺ',
    explanation: 'Allah spoke to Prophet Musa ﷺ at the valley of Tuwa.',
    hint: 'He is known as Kalimullah.',
    sourceNote: 'Qur’an — Musa at Tuwa.',
  },
];
