import type { GameQuestion } from '../types';

/** Basic Salah knowledge — undisputed essentials for children and families. */
export const SALAH_QUESTIONS: GameQuestion[] = [
  {
    id: 'salah-mc-1',
    gameId: 'salah',
    category: 'salah',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'How many obligatory daily prayers are there?',
    choices: [
      { id: 'a', label: '3' },
      { id: 'b', label: '4' },
      { id: 'c', label: '5' },
      { id: 'd', label: '7' },
    ],
    correctChoiceId: 'c',
    explanation: 'Muslims pray five obligatory prayers every day.',
    hint: 'It is more than four.',
  },
  {
    id: 'salah-mc-2',
    gameId: 'salah',
    category: 'salah',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Which prayer is prayed at dawn?',
    choices: [
      { id: 'a', label: 'Fajr' },
      { id: 'b', label: 'Maghrib' },
      { id: 'c', label: 'Isha' },
    ],
    correctChoiceId: 'a',
    explanation: 'Fajr is the early morning prayer before sunrise.',
    hint: 'It is the first prayer of the day.',
  },
  {
    id: 'salah-mc-3',
    gameId: 'salah',
    category: 'salah',
    ageGroups: [],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Which direction do Muslims face in Salah?',
    choices: [
      { id: 'a', label: 'The Qiblah (toward the Ka‘bah)' },
      { id: 'b', label: 'Any random direction' },
      { id: 'c', label: 'Toward the nearest tree' },
    ],
    correctChoiceId: 'a',
    explanation: 'Muslims face the Qiblah — toward the Ka‘bah in Makkah.',
    hint: 'It is connected to the Ka‘bah.',
  },
  {
    id: 'salah-mc-4',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Which prayer is prayed just after sunset?',
    choices: [
      { id: 'a', label: 'Maghrib' },
      { id: 'b', label: 'Fajr' },
      { id: 'c', label: 'Dhuhr' },
    ],
    correctChoiceId: 'a',
    explanation: 'Maghrib is prayed after the sun has set.',
    hint: 'It comes after sunset.',
  },
  {
    id: 'salah-mc-5',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'What is the midday prayer called?',
    choices: [
      { id: 'a', label: 'Dhuhr' },
      { id: 'b', label: 'Isha' },
      { id: 'c', label: 'Fajr' },
    ],
    correctChoiceId: 'a',
    explanation: 'Dhuhr is the midday prayer.',
    hint: 'It is prayed after the sun passes its highest point.',
  },
  {
    id: 'salah-mc-6',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Which prayer is the night prayer?',
    choices: [
      { id: 'a', label: 'Isha' },
      { id: 'b', label: 'Fajr' },
      { id: 'c', label: 'Asr' },
    ],
    correctChoiceId: 'a',
    explanation: 'Isha is the night prayer.',
    hint: 'It is the last of the five daily prayers.',
  },
  {
    id: 'salah-mc-7',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Before starting Salah, Muslims should…',
    choices: [
      { id: 'a', label: 'Have wudu and face the Qiblah' },
      { id: 'b', label: 'Eat a big meal first' },
      { id: 'c', label: 'Turn away from the Qiblah' },
    ],
    correctChoiceId: 'a',
    explanation: 'We prepare with wudu and face the Qiblah before praying.',
    hint: 'Think about purity and direction.',
  },
  {
    id: 'salah-mc-8',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['teen_15_17', 'adult_18_plus'],
    difficulty: 4,
    type: 'multiple_choice',
    prompt: 'Asr is prayed…',
    choices: [
      { id: 'a', label: 'In the afternoon' },
      { id: 'b', label: 'At dawn' },
      { id: 'c', label: 'Only on Fridays' },
    ],
    correctChoiceId: 'a',
    explanation: 'Asr is the afternoon prayer among the five daily prayers.',
    hint: 'It comes after Dhuhr.',
  },
  {
    id: 'salah-order-1',
    gameId: 'salah',
    category: 'salah',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'ordering',
    prompt: 'Put the five daily prayers in order from morning to night.',
    orderItems: [
      { id: '1', label: 'Fajr' },
      { id: '2', label: 'Dhuhr' },
      { id: '3', label: 'Asr' },
      { id: '4', label: 'Maghrib' },
      { id: '5', label: 'Isha' },
    ],
    explanation: 'The order is Fajr, Dhuhr, Asr, Maghrib, then Isha.',
    hint: 'Start with Fajr at dawn.',
  },
];
