import type { GameQuestion } from '../types';

/**
 * Educational wudu content for children.
 * Uses a widely taught complete sequence for learning games.
 * Obligatory pillars and school-specific details are not presented as disputed rulings.
 */
export const WUDU_QUESTIONS: GameQuestion[] = [
  {
    id: 'wudu-mc-1',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_3_6', 'child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'What do Muslims do before Salah to become clean?',
    choices: [
      { id: 'a', label: 'Wudu' },
      { id: 'b', label: 'Sleep' },
      { id: 'c', label: 'Run' },
    ],
    correctChoiceId: 'a',
    explanation: 'Wudu is washing certain parts of the body before prayer.',
    hint: 'It is a special washing before prayer.',
    sourceNote: 'Basic fiqh education — purification before Salah.',
  },
  {
    id: 'wudu-mc-2',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_3_6', 'child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Which of these is part of making wudu?',
    choices: [
      { id: 'a', label: 'Washing the face' },
      { id: 'b', label: 'Watching TV' },
      { id: 'c', label: 'Eating candy' },
    ],
    correctChoiceId: 'a',
    explanation: 'Washing the face is an important part of wudu.',
    hint: 'Think about washing for prayer.',
  },
  {
    id: 'wudu-mc-3',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'In wudu, we also wash our…',
    choices: [
      { id: 'a', label: 'Arms up to the elbows' },
      { id: 'b', label: 'Hair only' },
      { id: 'c', label: 'Shoes' },
    ],
    correctChoiceId: 'a',
    explanation: 'Muslims wash the arms up to the elbows during wudu.',
    hint: 'From the hands toward the elbows.',
  },
  {
    id: 'wudu-mc-4',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'What do we wipe in wudu?',
    choices: [
      { id: 'a', label: 'The head' },
      { id: 'b', label: 'The back' },
      { id: 'c', label: 'The knees only' },
    ],
    correctChoiceId: 'a',
    explanation: 'Wiping the head (masah) is part of wudu.',
    hint: 'It is done with wet hands on the head.',
  },
  {
    id: 'wudu-mc-5',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Why do Muslims perform wudu?',
    choices: [
      { id: 'a', label: 'To prepare for Salah with purity' },
      { id: 'b', label: 'To win a race' },
      { id: 'c', label: 'To skip prayer' },
    ],
    correctChoiceId: 'a',
    explanation: 'Wudu helps us prepare for Salah in a state of purity.',
    hint: 'It is connected to prayer.',
  },
  {
    id: 'wudu-order-1',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_7_10', 'child_11_14', 'teen_15_17', 'adult_18_plus'],
    difficulty: 2,
    type: 'ordering',
    prompt: 'Put these wudu steps in a good learning order.',
    orderItems: [
      { id: '1', label: 'Wash the hands' },
      { id: '2', label: 'Wash the face' },
      { id: '3', label: 'Wash the arms' },
      { id: '4', label: 'Wipe the head' },
      { id: '5', label: 'Wash the feet' },
    ],
    explanation:
      'A helpful learning order: hands, face, arms, wipe the head, then wash the feet.',
    hint: 'Start with the hands, then the face.',
    sourceNote:
      'Simplified educational sequence for children; school-specific details may vary.',
  },
  {
    id: 'wudu-order-2',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['child_3_6', 'child_7_10'],
    difficulty: 1,
    type: 'ordering',
    prompt: 'What comes first when starting wudu?',
    orderItems: [
      { id: '1', label: 'Wash hands' },
      { id: '2', label: 'Wash face' },
      { id: '3', label: 'Wash feet' },
    ],
    explanation: 'We begin by washing the hands, then continue with the face and feet.',
    hint: 'Hands come before the face.',
  },
  {
    id: 'wudu-mc-6',
    gameId: 'wudu',
    category: 'wudu',
    ageGroups: ['teen_15_17', 'adult_18_plus', 'child_11_14'],
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Which body parts are washed during wudu?',
    choices: [
      { id: 'a', label: 'Face, arms, and feet (and the head is wiped)' },
      { id: 'b', label: 'Only the hair' },
      { id: 'c', label: 'Only the elbows' },
    ],
    correctChoiceId: 'a',
    explanation: 'In wudu we wash the face, arms, and feet, and we wipe over the head.',
    hint: 'Remember wash vs wipe.',
  },
];
